# Generated by Django 4.2 on 2023-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='feature',
            field=models.IntegerField(blank=True, choices=[(1, 'Three D Projector'), (2, 'Dolby Sound')]),
        ),
    ]
