# Generated by Django 4.2 on 2023-04-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_screen_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theatre',
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.screen'),
            preserve_default=False,
        ),
    ]
