# Generated by Django 4.2 on 2023-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_showseat_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='payment',
            new_name='payments',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='seat',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
