# Generated by Django 4.2 on 2023-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_payment_ticket_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
